package com.vortexbird.reto.util.constants;

public class ConstantesGenerales {
    public  static  final String LLAVE_CIFRADO ="ZXlKaGJHY2lPaUpJVXpVeE1pSjkuZXlKU2IyeGxJam9pUVdSdGFXNGlMQ0pKYzNOMVpYSWlPaUpKYzNOMVpYSWlMQ0pWYzJWeWJtRnRaU0k2SWtwaGRtRkpibFZ6WlNJc0ltVjRjQ0k2TVRjeE9EZ3hOVEkzTnl3aWFXRjBJam94TnpFNE9ERTFNamMzZlEuMDF1M0tDbk5RWjFOdEc2SFhLQmtXdFg0UG1FN3YxQ19VVGhqOE5aQkhNd0k3RVhpWEF6WFZZU3pKbEJYT09JN3NFLS1NUUVFbnhQSnNQRmtPUk92c3c=";
    public static final Integer TIEMPO_VALIDEZ_TOKEN_MILLIS = 86400000;
}
